agent_string: 'Perly_Bot/v2'
should_emit: {
  age_threshold_secs: 86400 # one day
}
media: {
  'Perly::Bot::Media::JSON': {
    link_limit: 100,
    filepath: /tmp/links.json
  }
}
feeds: {
  filepath: /tmp/feeds.yml
}
